JotAFish/JotAFish/Controllers/UploadController.cs
using JotAFish.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using System.Web.WebPages;

namespace JotAFish.Controllers
{
    public class UploadController : Controller
    {
        List<string> pathList = new List<string>();
        //GET: Upload
        public ActionResult UploadImage()
        {
            MetaData mdImg = new MetaData();
            mdImg.uploadImg();
            ViewBag.newFileName = mdImg.newFileName;
            ViewBag.newLocation = mdImg.newLocation;
            ViewBag.imagePath = mdImg.imagePath;
            ViewBag.Date = mdImg.dateNoTime;
            ViewBag.Lat = mdImg.Lat;
            ViewBag.Lng = mdImg.Lng;
            ViewBag.PastWeather = mdImg.pastWeather;
            var myPics = new MyPictures();
            {
                myPics.Images = Directory.EnumerateFiles(Server.MapPath("/images/"))
                                  .Select(fn => "/images/" + Path.GetFileName(fn));
            }
            ViewBag.P = myPics.Images;
            foreach (var image in ViewBag.P)
            {
                pathList.Add("C:/Users/Kao/Documents/devcodecamp projects/JotAFish/JotAFish/JotAFish"+image);
            }
            mdImg.addPathToList(pathList);
            ViewBag.list = pathList;
            ViewBag.info = mdImg.newpastWeather;
            ViewBag.date = mdImg.date;
            return View();
        }
        public ActionResult ViewMyPictures()
        {
          
            return View();
        }
    }
}

JotAFish/JotAFish/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <script src="~/Scripts/map.js"></script>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Styles.Render("~/Content/css")
    <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Dancing+Script" />
    <link href="~/Content/Custom.css" rel="stylesheet" />
    @*<script src="~/Scripts/jquery-2.2.1.js"></script>*@
    @*<script src="~/Scripts/jquery.hoverfold.js"></script>
    <link href="~/Content/demo.css" rel="stylesheet" />
    <link href="~/Content/fallback.css" rel="stylesheet" />
    <link href="~/Content/normalize.css" rel="stylesheet" />
    <link href="~/Content/style_common.css" rel="stylesheet" />
    <link href="~/Content/style1.css" rel="stylesheet" />
    <link href="~/Content/style2.css" rel="stylesheet" />
    <link href="~/Content/style3.css" rel="stylesheet" />
    <link href="~/Content/style4.css" rel="stylesheet" />
    <link href="~/Content/style5.css" rel="stylesheet" />*@
    @*<script src="~/Scripts/modernizr.custom.69142.js"></script>
    @Scripts.Render("~/bundles/modernizr")*@
    @*<script src="https://cdn.firebase.com/js/client/2.2.1/firebase.js"></script>*@

    


</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("JotAFish", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @if (User.Identity.IsAuthenticated)
                    {
                            <li>@Html.ActionLink("Jots", "UploadImage", "Upload")</li>
                        
                    }


                    
                    @*<li>@Html.ActionLink("Home", "Index", "Home")</li>*@
                    @*<li>@Html.ActionLink("Upload", "Index", "Upload")</li>*@
                    @*<li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>*@
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer class="row bottom-left" style="position:fixed;bottom:0;">
            <p>&copy; @DateTime.Now.Year - JotAFish</p>
        </footer>
    </div>
    <script src="~/Scripts/map.js"></script>
    
    @RenderSection("scripts", required: false)
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDrlRR0sAV9e2hzFrWllEroS6Kgzfs7QaU&libraries=visualization&callback=initMap">
    </script>
</body>
</html>